name: app_one
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_swiper: ^1.1.6
  audioplayers: ^0.17.4
  # flutter_speed_dial: ^1.2.1
  painter: ^0.4.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.3.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/a-z kids.mp3
    - assets/bg1.png
    - assets/bg2.png
    - assets/bg3.png
    - assets/bg4.png
    - assets/bg5.png
    - assets/bg6.png
    - assets/bg7.png
    - assets/bg8.png
    - assets/bg9.png
    - assets/bg10.png
    - assets/bg11.png
    - assets/bg12.png
    - assets/bg13.png
    - assets/bg14.png
    - assets/bg15.png
    - assets/bg16.png
    - assets/bg17.png
    - assets/bg18.png
    - assets/bg19.png
    - assets/a.png
    - assets/b.png
    - assets/c.png
    - assets/d.png
    - assets/e.png
    - assets/f.png
    - assets/g.png
    - assets/h.png
    - assets/i.png
    - assets/j.png
    - assets/k.png
    - assets/l.png
    - assets/m.png
    - assets/n.png
    - assets/o.png
    - assets/p.png
    - assets/q.png
    - assets/r.png
    - assets/s.png
    - assets/t.png
    - assets/u.png
    - assets/v.png
    - assets/w.png
    - assets/x.png
    - assets/y.png
    - assets/z.png
    - assets/profile_icon.png
    - assets/menu_icon.png
    - assets/search_icon.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: poppins
    #   fonts:
    #     - asset: fonts/Poppins-Black.ttf
    #     - asset: fonts/Poppins-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Balsamiq_Sans
      fonts:
        - asset: fonts/BalsamiqSans-Bold.ttf
        - asset: fonts/BalsamiqSans-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
